name: Deploy to prod

on:
  push:

jobs:
  ping-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Notify server of commit
        run: curl -fSL "https://deltamodders.com/apiv1/internal/serverUpdate?key=${{ secrets.SERVER_UPDATE_KEY }}"

      - name: Wait 30 seconds
        run: sleep 30

      - name: Check server status
        run: curl -fSL "https://deltamodders.com/"
